version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: forensic-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forensicdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  forensic-analyzer:
    build: .
    container_name: forensic-analyzer-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/forensicdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data:
